setting for uploading to hackage

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,4 @@
+
 branches:
   only:
     - stable
@@ -28,6 +29,16 @@ install:
 script:
   - cabal configure -v2
   - cabal build
+  - cabal check
+  - cabal sdist
+  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+    cd dist/;
+    if [ -f "$SRC_TGZ" ]; then
+       cabal install --force-reinstalls "$SRC_TGZ";
+    else
+       echo "expected '$SRC_TGZ' not found";
+       exit 1;
+    fi
 
 notifications:
   slack: jaiyalas:rTERqdvyJZbXGRYxy3SLKAtq
